services:
  culturebridge:
    build:
      context: .
      dockerfile: Dockerfile
    image: culturebridge
    container_name: culturebridge
    restart: unless-stopped
    depends_on:
      - culturebridge_database
    env_file:
      - .env
    networks:
      - culturebridge
    volumes:
      - .:/app
      - .env:/app/.env

    ports:
      - 8001:8001
  
  culturebridge_database:
    image: postgres
    container_name: culturebridge_database
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - culturebridge
    volumes:
      - culturebrdige_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  culturebridge_celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: culturebridge_celery
    container_name: culturebridge_celery
    restart: unless-stopped
    depends_on:
      - culturebridge_database
      - culturebridge_redis
      - culturebridge
    command: celery -A culturebridge.celery worker --loglevel=info -E
    env_file:
      - .env
    networks:
      - culturebridge
    volumes:
      - .:/app
      - .env:/app/.env

  culturebridge_redis:
    image: redis:alpine
    container_name: culturebridge_redis
    restart: unless-stopped
    networks:
      - culturebridge
    ports:
      - 6380:6379
    env_file:
      - .env

networks:
  culturebridge:

volumes:
  culturebrdige_data: