# Generated by Django 5.1.2 on 2025-02-25 13:21

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', related_query_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('stundent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', related_query_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_students', models.IntegerField(null=True)),
                ('including_me', models.BooleanField(default=False, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('CHILD (5-8)', 'CHILD (5-8)'), ('CHILD (9-12)', 'CHILD 9-12'), ('TEENAGER (13-17)', 'TEENAGER (13-17)'), ('ADULT (18-Above)', 'ADULT (18-Above)')], default='ADULT (18-Above)', max_length=50)),
                ('reason', models.CharField(blank=True, help_text='why do you want to take this training', max_length=255)),
                ('personality', models.CharField(blank=True, choices=[('INTROVERT', 'INTROVERT'), ('EXTROVERT', 'EXTROVERT'), ('AMBIVERT', 'AMBIVERT')], default='INTROVERT', max_length=50)),
                ('self_description', models.JSONField(blank=True, default=list, help_text='Three words that best describe you', null=True, validators=[utils.validators.BaseValidator.validate_self_description])),
                ('confidence_level', models.IntegerField(blank=True, choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE')], null=True)),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.training')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
