# Generated by Django 5.1.2 on 2025-02-25 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainingform_confidence_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='training',
            name='stundent',
        ),
        migrations.AddField(
            model_name='training',
            name='instructor_id',
            field=models.CharField(blank=True, help_text="instructor's id", max_length=255),
        ),
        migrations.AddField(
            model_name='training',
            name='language',
            field=models.CharField(choices=[('YORUBA', 'YORUBA'), ('HAUSA', 'HAUSA'), ('IGBO', 'IGBO'), ('ENGLISH', 'ENGLISH')], default='YORUBA', max_length=50),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user who enrolled for the training', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterModelTable(
            name='training',
            table='trainings',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sub_modules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.training')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.DeleteModel(
            name='TrainingForm',
        ),
    ]
