# Generated by Django 5.1.2 on 2025-02-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_training_options_remove_training_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
