# Generated by Django 5.1.2 on 2025-03-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_training_end_date_alter_training_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='training',
        ),
        migrations.AddField(
            model_name='course',
            name='language_category',
            field=models.CharField(blank=True, choices=[('YORUBA', 'YORUBA'), ('HAUSA', 'HAUSA'), ('IGBO', 'IGBO'), ('ENGLISH', 'ENGLISH')], max_length=255),
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_instructor_id', models.CharField(blank=True, help_text="instructor's id", max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.training')),
                ('user', models.ForeignKey(blank=True, help_text="\n        who's taking the course.\n        (The person who enrolled might not be the one taking the course)\n        ", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
                'db_table': 'training_courses',
            },
        ),
    ]
