# Generated by Django 5.1.2 on 2025-03-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_training_course_language_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('FREE', 'FREE'), ('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('SUCCESSFUL', 'SUCCESSFUL')], default='PENDING', max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'NGN'), ('USD', 'USD')], default='USD', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.training')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
