# Generated by Django 5.1.2 on 2025-03-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_training_payment_status_paymenttransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transaction',
        ),
    ]
