# Generated by Django 5.1.2 on 2025-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='txn_reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
