# Generated by Django 5.1.2 on 2025-04-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymenttransaction_txn_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='_choice',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', max_length=255),
        ),
        migrations.AddField(
            model_name='training',
            name='_type',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='ONLINE', max_length=255),
        ),
    ]
