# Generated by Django 5.1.2 on 2025-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
