# Generated by Django 5.1.2 on 2025-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='links',
            field=models.JSONField(default=list),
        ),
    ]
