# Generated by Django 5.1.2 on 2026-02-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_course_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='amount',
            field=models.FloatField(default=0.0, help_text="amount to be paid for the training, if it's a paid training", null=True),
        ),
    ]
