# Generated by Django 5.1.2 on 2026-05-04 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_training_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'country asset',
                'verbose_name_plural': 'country assets',
                'db_table': 'country_asset',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('FLUTTERWAVE', 'FLUTTERWAVE'), ('PAYSTACK', 'PAYSTACK'), ('ANCHOR', 'ANCHOR'), ('SQUAD', 'SQUAD'), ('STRIPE', 'STRIPE')], default='FLUTTERWAVE', max_length=255, null=True)),
                ('expires_in', models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 53, 45, 516513, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'payment_platform_token',
                'verbose_name_plural': 'payment_platform_tokens',
                'db_table': 'payment_platform_token',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
