# Generated by Django 5.1.2 on 2026-05-04 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_countryasset_paymentplatformtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplatformtoken',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name': 'payment platform token', 'verbose_name_plural': 'payment platform tokens'},
        ),
        migrations.AlterField(
            model_name='paymentplatformtoken',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 15, 28, 3, 115999, tzinfo=datetime.timezone.utc)),
        ),
    ]
