# Generated by Django 5.1.2 on 2024-11-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_vlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='blog image', null=True, upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='vlog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
