# Generated by Django 5.1.2 on 2025-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_image_vlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
