# Generated by Django 5.1.2 on 2024-11-06 16:26

from django.db import migrations
from apps.users.management.commands.create_adminusers import Command

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            Command().handle, migrations.RunPython.noop
        )
    ]
