# Generated by Django 5.1.2 on 2025-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
