# Generated by Django 5.1.2 on 2025-03-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_meta_alter_user_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_taught',
            field=models.CharField(blank=True, choices=[('YORUBA', 'YORUBA'), ('HAUSA', 'HAUSA'), ('IGBO', 'IGBO'), ('ENGLISH', 'ENGLISH')]),
        ),
    ]
