# Generated by Django 5.1.2 on 2026-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_language_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('campaign_source', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('YORUBA', 'YORUBA'), ('HAUSA', 'HAUSA'), ('IGBO', 'IGBO'), ('ENGLISH', 'ENGLISH')], default='ENGLISH', max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'campaign user',
                'verbose_name_plural': 'campaign users',
                'db_table': 'campaign_users',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
