# Generated by Django 5.1.2 on 2026-01-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_campaignuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
