# Generated by Django 5.1.2 on 2026-05-04 14:43

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_campaignuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[utils.validators.BaseValidator.validate_phone_number]),
        ),
    ]
